name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: text_analysis Test
      id: text_analysis-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: text_analysis Test
        setup-command: ''
        command: python test_main.py
        timeout: 2
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEXT_ANALYSIS-TEST_RESULTS: "${{steps.text_analysis-test.outputs.result}}"
      with:
        runners: text_analysis-test
